name: Robotics Club Blog
url: https://github.com/shashikg/robotics_club_blog/tree/master/docs
paginate: 5
paginate_path: "/page:num/"
plugins: 
- jekyll-paginate

markdown: kramdown

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

highlighter: rouge
